// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkIlz-FARajb3NUaMsje-Vae2TqqGwboo',
    appId: '1:769730745773:web:9c3da5c4e947668db27d24',
    messagingSenderId: '769730745773',
    projectId: 'instagram-clone-01-a57bc',
    authDomain: 'instagram-clone-01-a57bc.firebaseapp.com',
    storageBucket: 'instagram-clone-01-a57bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh1lPgoIEOmKOczfvsVS5EEYwX3sdq--Y',
    appId: '1:769730745773:android:5530861bd6f6cf0cb27d24',
    messagingSenderId: '769730745773',
    projectId: 'instagram-clone-01-a57bc',
    storageBucket: 'instagram-clone-01-a57bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWnFQhNyyhmXAkRKmBIcZwGSjptBEfi0',
    appId: '1:769730745773:ios:1ac8705724adad5db27d24',
    messagingSenderId: '769730745773',
    projectId: 'instagram-clone-01-a57bc',
    storageBucket: 'instagram-clone-01-a57bc.appspot.com',
    iosClientId: '769730745773-dvgmt6bak5tdpf1huv8m1unoctgeuim8.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoWnFQhNyyhmXAkRKmBIcZwGSjptBEfi0',
    appId: '1:769730745773:ios:13f3f8a7e50ca52ab27d24',
    messagingSenderId: '769730745773',
    projectId: 'instagram-clone-01-a57bc',
    storageBucket: 'instagram-clone-01-a57bc.appspot.com',
    iosClientId: '769730745773-m0l6antcntdu1bo7jnqf3a68tdbh73th.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
